name: RAG_Chat_Bot
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h500dc9f_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311h1854d6b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h21dd04a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=21.1.5=h3d58e20_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - liblzma=5.8.1=hd471939_2
  - liblzma-devel=5.8.1=hd471939_2
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.0=h86bffb9_0
  - libzlib=1.3.1=hd23fc13_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h230baf5_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311h62e9434_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h74c2667_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - pyzmq=27.1.0=py311h0ab6910_0
  - readline=8.3=h49f2429_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hca40e9d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=hf689a15_2
  - tornado=6.5.2=py311hf197a57_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h357f2ed_2
  - xz-gpl-tools=5.8.1=h357f2ed_2
  - xz-tools=5.8.1=hd471939_2
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - asgiref==3.10.0
      - attrs==25.4.0
      - azure-ai-agents==1.2.0b6
      - azure-ai-inference==1.0.0b9
      - azure-ai-projects==1.0.0
      - azure-common==1.1.28
      - azure-core==1.36.0
      - azure-core-tracing-opentelemetry==1.0.0b12
      - azure-cosmos==4.14.1
      - azure-identity==1.25.1
      - azure-search-documents==11.6.0
      - azure-storage-blob==12.27.1
      - bert-score==0.3.13
      - bokeh==3.4.3
      - cachetools==6.2.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - databricks-sdk==0.73.0
      - dataclasses-json==0.6.7
      - datasets==4.4.1
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - distro==1.9.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - evaluate==0.4.6
      - faiss-cpu==1.10.0
      - fastapi==0.121.1
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - giskard==2.18.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - greenlet==3.2.4
      - griffe==1.15.0
      - groq==0.33.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - identify==2.6.15
      - idna==3.11
      - instructor==1.13.0
      - isodate==0.7.2
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langchain==1.0.5
      - langchain-azure-ai==1.0.3
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.4
      - langchain-openai==1.0.2
      - langchain-text-splitters==1.0.0
      - langdetect==1.0.9
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.2
      - langgraph-sdk==0.2.9
      - langsmith==0.4.42
      - litellm==1.65.8
      - llvmlite==0.45.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mixpanel==5.0.0
      - mlflow-skinny==3.6.0
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - networkx==3.5
      - nodeenv==1.9.1
      - num2words==0.5.14
      - numba==0.62.1
      - numpy==1.26.4
      - openai==2.7.2
      - opentelemetry-api==1.38.0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pre-commit==4.4.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyjwt==2.10.1
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - ragas==0.3.9
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scikit-network==0.33.3
      - scipy==1.11.4
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - sqlparse==0.5.3
      - starlette==0.49.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.2.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - ty==0.0.1a26
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - virtualenv==20.35.4
      - watchfiles==1.1.1
      - websockets==15.0.1
      - xxhash==3.6.0
      - xyzservices==2025.10.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/RAG_Chat_Bot
